version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- EXTRACTOR 1 ---
  extractor_1:
    build: ./extractor
    container_name: extractor_1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # Map internal port 8000 to external 8001
    ports:
      - "8001:8000"
    environment:
      # Use Key #1
      - RIOT_API_KEY=${RIOT_API_KEY_1}
    depends_on:
      - db
      - redis

  # --- EXTRACTOR 2 ---
  extractor_2:
    build: ./extractor
    container_name: extractor_2
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # Map to 8004 to avoid conflict
    ports:
      - "8004:8000"
    environment:
      # Use Key #2
      - RIOT_API_KEY=${RIOT_API_KEY_2}
    depends_on:
      - db
      - redis

  transformer_loader:
    build: ./transformer_loader
    container_name: transformer_loader
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    depends_on:
      - db

  api_service:
    build: ./api_service
    container_name: api_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8003:8000"
    environment:
      # API Service only needs 1 key (any valid key) just to resolve PUUIDs
      - RIOT_API_KEY=${RIOT_API_KEY_1}
    depends_on:
      - db
      - redis

  dashboard:
    build: ./dashboard
    container_name: dashboard
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api_service:8000
    depends_on:
      - api_service

volumes:
  mongo_data: